{% set name = "jom" %}
{% set version = "1.1.4" %}
{% set sha256 = "d533c1ef49214229681e90196ed2094691e8c4a0a0bef0b2c901debcb562682b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://download.qt.io/official_releases/jom/jom_{{ version.replace('.', '_') }}.zip
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [not win]
  script:
    - cp *.bat %LIBRARY_BIN%\
    - cp *.exe %LIBRARY_BIN%\
    - cp *.xml %LIBRARY_BIN%\

test:
  commands:
    - jom /VERSION

about:
  home: https://wiki.qt.io/Jom
  license: GPLv3
  license_family: GPL
  license_file: {{ RECIPE_DIR }}/LICENSE
  summary: 'jom is a clone of nmake to support the execution of multiple independent commands in parallel'

extra:
  recipe-maintainers:
    - isuruf
